baseURL = 'https://bourbonbourbon.github.io/'
languageCode = 'en-us'
title = "bourbonbourbon's website"

[params]
Name = "Siddiqui Abdul Rahman"
About = "I am a computer engineering student interested in __DevOps__ & __CloudOps__."
Email = "abdulrahman75157@gmail.com"
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/bourbonbourbon"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/siddiqui-abdul-rahman-638a60210"